In [ ]:
for num in range(1, 6):
    factorial = 1
    for i in range(1, num + 1):
        factorial *= i
    print("Factorial of", num, "is", factorial)

Factorial of 1 is 1
Factorial of 2 is 2
Factorial of 3 is 6
Factorial of 4 is 24
Factorial of 5 is 120


In [ ]:
for num in range(2, 21):
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(num, "is a prime number")
    else:
        print(num, "is not a prime number")

2 is a prime number
3 is a prime number
4 is not a prime number
5 is a prime number
6 is not a prime number
7 is a prime number
8 is not a prime number
9 is not a prime number
10 is not a prime number
11 is a prime number
12 is not a prime number
13 is a prime number
14 is not a prime number
15 is not a prime number
16 is not a prime number
17 is a prime number
18 is not a prime number
19 is a prime number
20 is not a prime number


In [ ]:
sum_even = 0
for num in range(1, 21):
    if num % 2 == 0:
        sum_even += num
print("Sum of even numbers from 1 to 20 is", sum_even)

Sum of even numbers from 1 to 20 is 110


In [ ]:
class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

    def start_engine(self):
        pass

class car(Vehicle):
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self.year = year

    def stop_engine(self):
            print(f" the make name is {self.make} and the model name is {self.model} and the year name is {self.year}")

class Motorcycle(Vehicle):
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self.year = year

    def stop_enginename(self):
        print(f"the make name is {self.make} and the model name is {self.model} and the year name is {self.year}")

In [ ]:
car1=car( "toyota","xuv 700","2024")

In [ ]:
car1.stop_engine()

 the make name is toyota and the model name is xuv 700 and the year name is 2024


In [ ]:
Motorcycle1=Motorcycle("bajaj","110cc","2024",)

In [ ]:
Motorcycle1.stop_enginename()

the make name is bajaj and the model name is 110cc and the year name is 2024


In [ ]:
class Parent:
    def __init__(self, name):
        self.name = name

    def greet(self):
        print(f"Hello from {self.name}")

class Child(Parent):
    def __init__(self, name, age):
        super().__init__(name)
        self.age = age

    def greet(self):
        super().greet()
        print(f"I am {self.age} years old.")

child = Child("harsh", 18)
child.greet()


Hello from harsh
I am 18 years old.


In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
data = {
      "SNo":{
    "0":1,
    "1":2,
    "2":3,
    "3":4,
    "4":5,
    "5":6
  },
      "rollNo":{
    "0":10,
    "1":20,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
      "name":{
    "0":"harsh",
    "1":"vipul",
    "2":"nitin",
    "3":"pritam",
    "4":"naman",
    "5":"anuj"
  },
      "possition":{
    "0":"A",
    "1":"A+",
    "2":"B",
    "3":"B+",
    "4":"B+",
    "5":"A"
  },

}

df = pd.DataFrame(data)

print(df)

   SNo  rollNo    name possition
0    1      10   harsh         A
1    2      20   vipul        A+
2    3      60   nitin         B
3    4      45  pritam        B+
4    5      45   naman        B+
5    6      60    anuj         A


In [ ]:
def load_data(file_path):
    try:
        data = pd.read_csv(file_path)
        print(f"Data loaded successfully from {file_path}")
        return data
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

file_path = 'iris.csv'
data = load_data(file_path)
if data is not None:
    print(data.head())

Error loading data: name 'pd' is not defined


In [ ]:
def calculator(a, b, operation):
    if operation == 'add':
        return a + b
    elif operation == 'subtract':
        return a - b
    elif operation == 'multiply':
        return a * b
    elif operation == 'divide':
        return a / b if b != 0 else "Cannot divide by zero"
    else:
        return "Invalid operation"

a, b = 15, 5
operation = 'multiply'
print(f"The result of {operation} is: {calculator(a, b, operation)}")

The result of multiply is: 75


In [ ]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

print(bubble_sort([64, 34, 25, 12, 22, 11, 90]))


[11, 12, 22, 25, 34, 64, 90]


In [ ]:
import pandas as pd

In [ ]:
pd.read_csv('iris.csv')

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df = pd.read_csv('iris.csv')
print(df.shape)

(150, 5)


In [ ]:
df = pd.read_csv('iris.csv')
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [ ]:
df = pd.read_csv('iris.csv')
print(df.index)

RangeIndex(start=0, stop=150, step=1)


In [ ]:
df = pd.read_csv('iris.csv')
print(df.filter(items=["sepal_width","petal_width"]))

     sepal_width  petal_width
0            3.5          0.2
1            3.0          0.2
2            3.2          0.2
3            3.1          0.2
4            3.6          0.2
..           ...          ...
145          3.0          2.3
146          2.5          1.9
147          3.0          2.0
148          3.4          2.3
149          3.0          1.8

[150 rows x 2 columns]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

max_value = np.max(arr)
min_value = np.min(arr)

print(f"Max: {max_value}, Min: {min_value}")

Max: 5, Min: 1


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
even = np.arange(0, 20, 2)
print(even)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_arr = arr.reshape((3, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2
print(result)

result = arr1 * arr2
print(result)


[5 7 9]
[ 4 10 18]
